application: shobbus
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: handler_htmls.course_tracker_main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest